title: "Home"
name: "Giulia Giannini"
description: "Cosmologist • Weak Lensing • DES, Euclid & LSST-DESC"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

logo: "/assets/DSC02069_cropped3_mini_copy.jpeg"

# URL base (lascia così per ora)
url: "https://giuliagiannini.github.io"
baseurl: ""

# GitHub Pages settings
plugins:
  - jekyll-include-cache

# Sass settings for custom CSS
sass:
  style: compressed

# Layout di default per le pagine
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      author: GiuliaGiannini
