title: ""
subtitle: "Giulia Giannini"
logo: "assets/DSC02069_cropped3_mini_copy.jpeg"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# URL base (lascia cos√¨ per ora)
url: "https://giuliagiannini.github.io"
baseurl: ""

# GitHub Pages settings
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme


# Sass settings for custom CSS
sass:
  style: compressed

google_fonts:
  - name: "Work Sans"
    weights: "400,500,600"
  - name: "Source Sans 3"
    weights: "400,600"
    
# Layout di default per le pagine
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      # author_profile: true
      # author: GiuliaGiannini_onlypic
